apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnb
  template:
    metadata:
      labels:
        app: gnb
    spec:
      containers:
      - name: gnb
        image: rdefosseo/ueransim:latest
        command: ["/UERANSIM/build/nr-gnb", "-c", "/UERANSIM/config/gnb-config.yaml"]
        ports:
        - containerPort: 38412
---
apiVersion: v1
kind: Service
metadata:
  name: gnb-service
  namespace: monitoring
spec:
  selector:
    app: gnb
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
  type: ClusterIP
