apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-controller
  namespace: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos
  template:
    metadata:
      labels:
        app: onos
    spec:
      containers:
      - name: onos
        image: onosproject/onos:2.5.0
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: onos-service
  namespace: orchestrator
spec:
  selector:
    app: onos
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: NodePort
