apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-amf
  namespace: oai-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: oaisoftwarealliance/oai-amf:v2.1.9
        ports:
        - containerPort: 38412
---
apiVersion: v1
kind: Service
metadata:
  name: amf-service
  namespace: oai-core
spec:
  selector:
    app: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
  type: ClusterIP
