apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nrf
  namespace: oai-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
      - name: nrf
        image: oaisoftwarealliance/oai-nrf:v2.1.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nrf-service
  namespace: oai-core
spec:
  selector:
    app: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
