apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-smf
  namespace: oai-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
      - name: smf
        image: oaisoftwarealliance/oai-smf:v2.1.9
        ports:
        - containerPort: 8805
---
apiVersion: v1
kind: Service
metadata:
  name: smf-service
  namespace: oai-core
spec:
  selector:
    app: smf
  ports:
    - protocol: UDP
      port: 8805
      targetPort: 8805
  type: ClusterIP
