apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-upf
  namespace: oai-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
      - name: upf
        image: oaisoftwarealliance/oai-upf:v2.1.9
        ports:
        - containerPort: 2152
---
apiVersion: v1
kind: Service
metadata:
  name: upf-service
  namespace: oai-core
spec:
  selector:
    app: upf
  ports:
    - protocol: UDP
      port: 2152
      targetPort: 2152
  type: ClusterIP
