apiVersion: v1
kind: Pod
metadata:
  name: xapp-database
spec:
  containers:
  - name: db
    image: timescale/timescaledb:latest-pg14
    env:
    - name: POSTGRES_PASSWORD
      value: admin
    ports:
    - containerPort: 5432